const lessons=[
{title:"El Escáner de Tiempo",intro:"Antes de pedirle más a la IA, descubre qué tareas repetitivas están consumiendo tu día.",exercise:"Anota durante 10 minutos todo lo que haces en un día normal. Marca con R las tareas repetitivas y con D las que podrías delegar.",prompt:"Actúa como mi analista de tiempo. Te daré una lista de tareas. Clasifícalas en: eliminar, automatizar, delegar o hacer personalmente. Explica brevemente cada decisión."},
{title:"El Organizador de Día",intro:"Convierte una lista desordenada en un plan realista.",exercise:"Escribe tus pendientes de mañana y añade cuánto tiempo crees que necesita cada uno.",prompt:"Organiza mi día con estas tareas: [PEGA AQUÍ]. Prioriza por impacto y urgencia, agrupa tareas similares y deja espacios razonables para imprevistos."},
{title:"El Redactor Instantáneo",intro:"Deja de empezar mensajes, correos y textos desde cero.",exercise:"Toma un mensaje que necesites enviar y escribe primero la idea en lenguaje natural.",prompt:"Convierte estas ideas en un mensaje claro, breve y profesional. Mantén mi intención y no inventes información: [PEGA AQUÍ]."},
{title:"El Analista de Información",intro:"Usa la IA para convertir información extensa en decisiones comprensibles.",exercise:"Pega un texto, noticia o documento que necesites entender y pide una síntesis accionable.",prompt:"Analiza la información siguiente. Devuélveme: resumen, hechos clave, riesgos, preguntas abiertas y acciones recomendadas. Separa hechos de inferencias: [PEGA AQUÍ]."},
{title:"El Generador de Ideas",intro:"Haz que la IA amplíe tus opciones sin sustituir tu criterio.",exercise:"Define un problema concreto y pide varias soluciones con ventajas y desventajas.",prompt:"Genera 10 soluciones para este problema: [PROBLEMA]. Ordénalas por tipo de enfoque y explica el principal beneficio y riesgo de cada una."},
{title:"El Delegador Universal",intro:"Aprende a entregar contexto, resultado esperado y límites.",exercise:"Elige una tarea que normalmente haces tú y describe qué resultado final necesitas.",prompt:"Voy a delegarte esta tarea: [TAREA]. Objetivo: [OBJETIVO]. Contexto: [CONTEXTO]. Restricciones: [LÍMITES]. Hazme las preguntas mínimas necesarias y después entrega el resultado listo para revisar."},
{title:"Tu Día Delegado",intro:"Combina los prompts anteriores en un sistema personal.",exercise:"Diseña tres tareas diarias que pasarán por tu asistente de IA.",prompt:"Ayúdame a diseñar mi sistema diario de IA. Mis tareas recurrentes son: [TAREAS]. Propón qué debo delegar, qué revisar personalmente y qué automatizar después."},
{title:"Reto práctico de 7 días",intro:"Convierte el aprendizaje en un hábito medible.",exercise:"Durante 7 días registra tarea, prompt utilizado, minutos ahorrados y resultado obtenido.",prompt:"Actúa como mi coach de productividad. Revisa este registro de 7 días: [REGISTRO]. Detecta patrones, estima qué tareas conviene sistematizar y propón mi siguiente experimento."}
];
export default function Lesson(){return <main><header><a href="/"><strong>ORVUX ACADEMY</strong></a><span>Cerebro Digital</span></header><section className="hero compact"><p className="eyebrow">AULA · CEREBRO DIGITAL</p><h1>Aprende haciendo.</h1><p className="lead">Cada módulo tiene una idea, un ejercicio y un prompt para llevarlo a tu vida real.</p></section><section className="content"><div className="lessonGrid">{lessons.map((l,i)=><article className="lessonCard" key={l.title}><span className="lessonNo">0{i+1}</span><h2>{l.title}</h2><p>{l.intro}</p><h3>Ejercicio</h3><p>{l.exercise}</p><h3>Prompt listo para copiar</h3><pre>{l.prompt}</pre><a className="cta secondary" href="/curso#pago">Marcar módulo como completado</a></article>)}</div><div className="nextStep"><h2>¿Terminaste los 8 módulos?</h2><p>Pasa a la evaluación final y demuestra que puedes aplicar el sistema a una situación real.</p><a className="cta" href="/curso/evaluacion">Ir a la evaluación</a></div></section><footer>© 2026 ORVUX Academy</footer></main>}